#!/usr/bin/env python
"""
Based on ionsval via Dorian Raymer
"""

USAGE="""
Command line tool for sending a state query to one EPU controller about one node.

Must be run from the top directory (./scripts/epu-node-error)

usage: ./scripts/epu-node-error sys_name broker_host controller_name node_id

sys_name: Unique sysname of this launch (it is also known as exchange_scope,
          in a cloudinit.d launch see the "common/deps*" file for this value).

broker_host: The hostname of the RabbitMQ broker, default port is assumed.

controller_name: Service name of the EPU Controller to invoke

node_id: the internal node_id to query about (IDs returned by epu-state)

"""

import os
import sys

import simplejson as json

from twisted.internet import defer
from twisted.internet import reactor

from epu.ionproc.epu_controller_client import EPUControllerClient
from epu.epucontroller import de_states
from epu import cei_events

from ion.util import procutils
import time
import traceback

import logging

@defer.inlineCallbacks
def state_one(targetname):


@defer.inlineCallbacks
def node_error(targetname, node_id):
    logging.info("Getting error for '%s' -> '%s'" % (targetname, node_id))
    client = EPUControllerClient(targetname=targetname)
    yield client.attach()
    result = yield client.node_error(node_id)
    if result:
        logging.info("Received error for '%s' -> '%s':\n\n%s\n\n" % (targetname, node_id, result))
    else:
        logging.info("Received no error for '%s' -> '%s'" % (targetname, node_id))

def finish_test(status, container):
    def stop_with_status(res, status):
        reactor.stop()
        global exit_status
        exit_status = status
    d = container.stopService()
    d.addBoth(stop_with_status, status)
    return d

@defer.inlineCallbacks
def run_node_error(targetname, node_id, sysname, broker_host, broker_vhost):
    from ion.core.cc import service
    config = service.Options()
    config['broker_host'] = broker_host
    config['broker_vhost'] = broker_vhost
    config['no_shell'] = True
    config['args'] = 'sysname=%s' % (sysname,)
    config['script'] = None
    container = service.CapabilityContainer(config)
    try:
        yield container.startService()
    except Exception:
        traceback.print_exc(file=sys.stdout)
        yield finish_test(2, container)
    try:
        yield node_error(targetname, node_id)
        yield finish_test(0, container)
    except Exception:
        traceback.print_exc(file=sys.stdout)
        yield finish_test(1, container)

def main(sysname, broker_host, targetname, node_id):
    global exit_status
    exit_status = 4
    broker_vhost='/'
    logging.basicConfig(level=logging.DEBUG)
    run_node_error(targetname, node_id, sysname, broker_host, broker_vhost)
    reactor.run()
    sys.exit(exit_status)

if __name__ == '__main__':
    if len(sys.argv) < 4:
        print USAGE
        sys.exit(64)
    args = sys.argv[1:]
    main(*args)
