#!/usr/bin/env python
"""
Based on ionsval via Dorian Raymer
"""

USAGE="""
Command line tool for sending a reconfigure invocation to an EPU Controller.

Must be run from the top directory (./scripts/epu-reconfigure)

usage: ./scripts/epu-reconfigure /path/to/messaging.conf controller_name json_file

messaging.conf: messaging configuration file parsable by epu.util

controller_name: Service name of the EPU Controller to invoke

json_file: Path to a JSON file containing the message content of the
           reconfigure operation.  See decision engine or administrator
           documentation for possible values, here is a sample of the
           common case of reconfiguring the number of workers:

           {"preserve_n":"3"}

"""

import os
import sys

import simplejson as json

from twisted.internet import defer
from twisted.internet import reactor

from ion.services.cei.epu_controller_client import EPUControllerClient
from ion.util import procutils
import epu.util

def reconfigure(_, targetname, payload_dict):
    client = EPUControllerClient(targetname=targetname)
    client.reconfigure(payload_dict)
    d = procutils.asleep(1)
    d.addCallbacks(exit_ok, exit_fail)
    return d

def exit_ok(result):
    return 0

def exit_fail(reason):
    reason.printTraceback()
    return 1

def container_error(reason):
    reason.printTraceback()
    return 2

def finish_test(status, container):
    def stop_with_status(res, status):
        reactor.stop()
        global exit_status
        exit_status = status
    d = container.stopService()
    d.addBoth(stop_with_status, status)
    return d

def run_reconfigure(messaging_conf, targetname, payload_dict):
    from ion.core.cc import service
    config = epu.util.create_container_config(messaging_conf)
    container = service.CapabilityContainer(config)
    d = container.startService()
    d.addCallback(reconfigure, targetname, payload_dict)
    d.addErrback(container_error)
    d.addCallback(finish_test, container)
    return d

def main(messaging_conf, targetname, json_file):
    global exit_status
    exit_status = 4

    if not os.path.exists(json_file):
        print "Cannot find the json file: %s" % json_file
        sys.exit(1)

    f = open(json_file)
    json_string = f.read()
    f.close()
    json_dict = json.loads(json_string)

    run_reconfigure(messaging_conf, targetname, json_dict)
    reactor.run()
    sys.exit(exit_status)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print USAGE
        sys.exit(64)
    args = sys.argv[1:]
    main(*args)
