#!/usr/bin/env python
"""
Based on ionsval via Dorian Raymer
"""

USAGE="""
Command line tool for sending a state check invocation to an EPU Controller and
waiting for it to move to STABLE.

Must be run from the top directory (./scripts/epu-state-wait)

usage: ./scripts/epu-state-wait controller_name sys_name broker_host

controller_name: Service name of the EPU Controller to invoke

sys_name: Unique sysname of this launch (it is also known as exchange_scope,
          in a cloudinit.d launch see the "common/deps*" file for this value).

broker_host: The hostname of the RabbitMQ broker, default port is assumed.

"""

import os
import sys

import simplejson as json

from twisted.internet import defer
from twisted.internet import reactor

from epu.ionproc.epu_reconfigure import EPUControllerClient
from epu.epucontroller import de_states
from ion.util import procutils
import time
import traceback

@defer.inlineCallbacks
def state_wait(targetname):
    print "\nGetting state.\n"
    client = EPUControllerClient(targetname=targetname)
    state = yield client.state()
    print "\nGot state:%s\n" % state

    #if state == de_states.UNKNOWN:
    #    raise Exception("DE does not support state")
    #else:
    #    while state != de_states.STABLE:
    #        time.sleep(4) # no shame
    #        state = yield client.state()
    #        print " - Got state: %s" % state
    #    print "Reached stable state: %s" % targetname

def finish_test(status, container):
    def stop_with_status(res, status):
        reactor.stop()
        global exit_status
        exit_status = status
    d = container.stopService()
    d.addBoth(stop_with_status, status)
    return d

@defer.inlineCallbacks
def run_state_wait(targetname, sysname, broker_host, broker_vhost):
    from ion.core.cc import service
    config = service.Options()
    config['broker_host'] = broker_host
    config['broker_vhost'] = broker_vhost
    config['no_shell'] = True
    config['args'] = 'sysname=%s' % (sysname,)
    config['script'] = None
    container = service.CapabilityContainer(config)
    try:
        print "\nStarting up.\n"
        yield container.startService()
    except Exception:
        traceback.print_exc(file=sys.stdout)
        defer.returnValue(2)
    try:
        yield state_wait(targetname)
        print "\nCleaning up.\n"
        yield finish_test()
    except Exception:
        traceback.print_exc(file=sys.stdout)
        defer.returnValue(1)

    yield finish_test(container)

def main(targetname, sysname, broker_host, broker_vhost='/'):
    global exit_status
    exit_status = 4
    run_state_wait(targetname, sysname, broker_host, broker_vhost)
    reactor.run()
    sys.exit(exit_status)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print USAGE
        sys.exit(64)
    args = sys.argv[1:]
    main(*args)
