#!/usr/bin/env python
"""
Based on ionsval via Dorian Raymer
"""

USAGE="""
Command line tool for sending a special reconfigure invocation to an EPU Controller.

Must be run from the top directory (./scripts/epu-reconfigure-n)

usage: ./scripts/epu-reconfigure-n /path/to/messaging.conf controller_name new_n

messaging.conf: messaging configuration file parsable by epu.util

controller_name: Service name of the EPU Controller to invoke, it must be using NPreservingEngine or similar

new_n: Integer to use for a "reconfigure preserve_n"

"""

import os
import sys

import simplejson as json

from twisted.internet import defer
from twisted.internet import reactor

from epu.ionproc.epu_controller_client import EPUControllerClient
from ion.util import procutils
import epu.util

import logging
import traceback

@defer.inlineCallbacks
def reconfigure(targetname, payload_dict):
    client = EPUControllerClient(targetname=targetname)
    yield client.attach()
    yield client.reconfigure_rpc(payload_dict)

def finish_test(status, container):
    def stop_with_status(res, status):
        reactor.stop()
        global exit_status
        exit_status = status
    d = container.stopService()
    d.addBoth(stop_with_status, status)
    return d

@defer.inlineCallbacks
def run_reconfigure(messaging_conf, targetname, payload_dict):
    from ion.core.cc import service
    config = epu.util.create_container_config(messaging_conf)
    container = service.CapabilityContainer(config)
    try:
        yield container.startService()
    except Exception:
        traceback.print_exc(file=sys.stdout)
        yield finish_test(2, container)
    try:
        yield reconfigure(targetname, payload_dict)
        yield finish_test(0, container)
    except Exception:
        traceback.print_exc(file=sys.stdout)
        yield finish_test(1, container)

def main(messaging_conf, targetname, new_n):
    global exit_status
    exit_status = 4
    payload_dict = {"preserve_n": "%s" % new_n}
    logging.basicConfig(level=logging.DEBUG)
    run_reconfigure(messaging_conf, targetname, payload_dict)
    reactor.run()
    sys.exit(exit_status)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print USAGE
        sys.exit(64)
    args = sys.argv[1:]
    main(*args)
