#!/usr/bin/env python

from epu.dashiproc.provisioner import ProvisionerClient
from epu.epucontroller import LaunchItem


client = ProvisionerClient()

launch_id = "myid"
deployable_type = "sleeper"
launch_description = {}
instanceid = "1111"
launch_description['work_consumer'] = LaunchItem(instanceid, "m1.large", "ec2-west", None)
launch_description['work_consumer'].instance_ids.append(instanceid)
client.provision(launch_id, deployable_type, launch_description, None)
client.query()
client.terminate_all()
client.query()
