#!/usr/bin/env python

import dashi.bootstrap as bootstrap

import time
import uuid

from epu.dashiproc.provisioner import ProvisionerClient
from epu.epucontroller.forengine import LaunchItem

def printcolor(string):
    COL = '\033[95m'
    ENDCOL = '\033[0m'
    print COL + string + ENDCOL

mytopic = "provisioner_client_%s" % uuid.uuid4()
dashi = bootstrap.dashi_connect(mytopic, amqp_uri="amqp://guest:guest@localhost/")

client = ProvisionerClient(dashi)
subscribers = (mytopic,)

launch_id = "myid"
deployable_type = "sleeper"
launch_description = {}
instanceid = "1111"
launch_description['work_consumer'] = LaunchItem(instanceid, "m1.large", "ec2-west", None)
launch_description['work_consumer'].instance_ids.append(instanceid)
printcolor("Provisioning (and waiting 60s)")

client.provision(launch_id, deployable_type, launch_description, subscribers)
time.sleep(60)
printcolor("Querying")
client.query()
printcolor("Dump stateing")
client.dump_state(nodes=[instanceid])
printcolor("Terminating")
client.terminate_nodes([instanceid])
