#!/usr/bin/env python

from epu.dashiproc.provisioner import ProvisionerService
from epu.localdtrs import LocalDTRS

dtrs = LocalDTRS("/opt/venv/dt-data/dt/")
#TODO: replace this with directorydtrs
 
ProvisionerService(dtrs=dtrs).start()
