#!/usr/bin/env python

from epu.dashiproc.provisioner import ProvisionerService
from epu.localdtrs import LocalDTRS

#TODO: replace this with a more sane default
dtrs = LocalDTRS("./epu/dashiproc/test/dt/")
 
provisioner = ProvisionerService(dtrs=dtrs)
provisioner.start()
